package com.sistema.blog.entities;

import jakarta.persistence.*;

/**
 * Entity representing a comment associated with a blog post.
 * Maps to the "comentarios" table in the database.
 */
@Entity
@Table(name = "comentarios")
public class Comment {

    /** Unique identifier for the comment. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /** Name of the author who wrote the comment. */
    @Column(name = "nombre")
    private String name;

    /** Email address of the comment author. */
    @Column(name = "email")
    private String email;

    /** Main text content of the comment. */
    @Column(name = "cuerpo")
    private String body;

    /** The blog post this comment belongs to. Loaded lazily. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "publicacion_id", nullable = false)
    private Post post;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-args constructor required by JPA.
     */
    public Comment() {
        super();
    }

    /**
     * Full constructor for creating a {@link Comment} with all fields.
     *
     * @param id    the unique identifier
     * @param name  the author's name
     * @param email the author's email
     * @param body  the comment text
     * @param post  the associated {@link Post}
     */
    public Comment(long id, String name, String email, String body, Post post) {
        super();
        this.id   = id;
        this.name = name;
        this.email = email;
        this.body  = body;
        this.post  = post;
    }

    // -------------------------------------------------------------------------
    // Getters & Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the comment's unique identifier.
     *
     * @return the comment ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the comment's unique identifier.
     *
     * @param id the comment ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the name of the comment's author.
     *
     * @return the author name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the comment's author.
     *
     * @param name the author name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the email of the comment's author.
     *
     * @return the author email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email of the comment's author.
     *
     * @param email the author email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the text body of the comment.
     *
     * @return the comment body
     */
    public String getBody() {
        return body;
    }

    /**
     * Sets the text body of the comment.
     *
     * @param body the comment body
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * Returns the {@link Post} this comment belongs to.
     *
     * @return the parent post
     */
    public Post getPost() {
        return post;
    }

    /**
     * Sets the {@link Post} this comment belongs to.
     *
     * @param post the parent post
     */
    public void setPost(Post post) {
        this.post = post;
    }

}
