package com.sistema.blog.entities;

import java.util.Set;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.*;

/**
 * Entity representing a blog post.
 * Maps to the "publicaciones" table in the database.
 * The title field is constrained to be unique.
 */
@Entity
@Table(
    name = "publicaciones",
    uniqueConstraints = { @UniqueConstraint(columnNames = { "titulo" }) }
)
public class Post {

    /** Unique identifier for the post. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Title of the post. Must be unique and cannot be null. */
    @Column(name = "titulo", nullable = false)
    private String title;

    /** Short description summarising the post. Cannot be null. */
    @Column(name = "descripcion", nullable = false)
    private String description;

    /** Full text content of the post. Cannot be null. */
    @Column(name = "contenido", nullable = false)
    private String content;

    /**
     * Set of {@link Comment}s belonging to this post.
     * Cascade all operations and remove orphan comments automatically.
     * Serialization is handled by the child side to avoid circular references.
     */
    @JsonBackReference
    @OneToMany(mappedBy = "post", cascade = CascadeType.ALL, orphanRemoval = true)
    private Set<Comment> comments;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Default no-args constructor required by JPA.
     */
    public Post() {
        super();
    }

    /**
     * Constructor for creating a {@link Post} with core fields.
     *
     * @param id          the unique identifier
     * @param title       the post title
     * @param description the short description
     * @param content     the full content
     */
    public Post(Long id, String title, String description, String content) {
        super();
        this.id          = id;
        this.title       = title;
        this.description = description;
        this.content     = content;
    }

    // -------------------------------------------------------------------------
    // Getters & Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the post's unique identifier.
     *
     * @return the post ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Sets the post's unique identifier.
     *
     * @param id the post ID
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Returns the title of the post.
     *
     * @return the post title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the title of the post.
     *
     * @param title the post title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Returns the short description of the post.
     *
     * @return the post description
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the short description of the post.
     *
     * @param description the post description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the full text content of the post.
     *
     * @return the post content
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the full text content of the post.
     *
     * @param content the post content
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Returns the set of comments associated with this post.
     *
     * @return the post's comments
     */
    public Set<Comment> getComments() {
        return comments;
    }

    /**
     * Sets the collection of comments for this post.
     *
     * @param comments the comments to associate
     */
    public void setComments(Set<Comment> comments) {
        this.comments = comments;
    }

}
