package com.sistema.blog.entities;

import jakarta.persistence.*;

/**
 * Entity representing a user role (e.g. ROLE_ADMIN, ROLE_USER).
 * Maps to the "roles" table in the database.
 */
@Entity
@Table(name = "roles")
public class Role {

    /** Unique identifier for the role. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /** Name of the role (e.g. "ROLE_ADMIN"). Limited to 60 characters. */
    @Column(length = 60)
    private String name;

    // -------------------------------------------------------------------------
    // Getters & Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the role's unique identifier.
     *
     * @return the role ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the role's unique identifier.
     *
     * @param id the role ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the name of the role.
     *
     * @return the role name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the name of the role.
     *
     * @param name the role name
     */
    public void setName(String name) {
        this.name = name;
    }

}
