package com.sistema.blog.entities;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.*;

/**
 * Entity representing an application user.
 * Maps to the "usuarios" table in the database.
 * Both username and email are constrained to be unique.
 */
@Entity
@Table(
    name = "usuarios",
    uniqueConstraints = {
        @UniqueConstraint(columnNames = { "username" }),
        @UniqueConstraint(columnNames = { "email"    })
    }
)
public class User {

    /** Unique identifier for the user. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;

    /** Unique username used for login. Stored in the "username" column. */
    @Column(name = "username")
    private String name;

    /** Unique email address of the user. */
    @Column(name = "email")
    private String email;

    /** Bcrypt-hashed password of the user. */
    private String password;

    /**
     * Set of {@link Role}s assigned to this user.
     * Fetched eagerly so that authorities are available during authentication.
     * Changes to roles cascade to the join table.
     */
    @ManyToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JoinTable(
        name = "usuarios_roles",
        joinColumns        = @JoinColumn(name = "usuario_id", referencedColumnName = "id"),
        inverseJoinColumns = @JoinColumn(name = "rol_id",     referencedColumnName = "id")
    )
    private Set<Role> roles = new HashSet<>();

    // -------------------------------------------------------------------------
    // Getters & Setters
    // -------------------------------------------------------------------------

    /**
     * Returns the user's unique identifier.
     *
     * @return the user ID
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the user's unique identifier.
     *
     * @param id the user ID
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Returns the user's username.
     *
     * @return the username
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the user's username.
     *
     * @param name the username
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the user's email address.
     *
     * @return the email
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the user's email address.
     *
     * @param email the email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Returns the user's hashed password.
     *
     * @return the hashed password
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the user's hashed password.
     *
     * @param password the hashed password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the set of roles assigned to this user.
     *
     * @return the user's roles
     */
    public Set<Role> getRoles() {
        return roles;
    }

    /**
     * Sets the roles assigned to this user.
     *
     * @param roles the roles to assign
     */
    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

}
